services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: dinero_publico
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55432:5432"
    volumes:
      - dinero_publico_pg:/var/lib/postgresql/data

volumes:
  dinero_publico_pg:
