import { useState } from 'react';
import { Check, Plus, X } from 'lucide-react';
import { universityOutcomeMetrics } from './data/outcomes';

const format = value => value == null ? 'No disponible' : `${Number(value).toFixed(2).replace('.', ',')}%`;

export default function UniversityCompare({ universities, offers, onBack }) {
  const [selected, setSelected] = useState([]);
  const toggle = short => setSelected(current => current.includes(short) ? current.filter(value => value !== short) : current.length < 4 ? [...current, short] : current);
  const cards = selected.map(short => { const university = universities.find(item => item.short === short); const list = offers.filter(offer => offer.short === short); const cutoffs = list.map(offer => offer.cutoff).sort((a, b) => a - b); const metrics = universityOutcomeMetrics[short] || {}; return { ...university, count: list.length, median: cutoffs[Math.floor(cutoffs.length / 2)], ...metrics }; });
  return <div className="app route-page university-compare-page"><header className="topbar"><button className="route-back" onClick={onBack}>← Volver al Atlas</button><div className="brand"><span className="brand-mark">A</span><span>ATLAS <i>UNIVERSITARIO</i></span></div><div className="year">MADRID · 2025—26</div></header><main><div className="route-kicker">COMPARADOR · UNIVERSIDADES PÚBLICAS</div><h1 className="route-title">Compara universidades</h1><p className="route-subtitle">Selecciona hasta cuatro opciones para comparar su oferta y el contexto académico publicado.</p><div className="university-compare-picker">{universities.map(university => <button key={university.short} className={selected.includes(university.short) ? 'selected' : ''} onClick={() => toggle(university.short)}><span className="uni-dot" style={{ background: university.color }}>{university.short}</span><span><strong>{university.name.replace('Universidad ', '')}</strong><small>{university.city}</small></span>{selected.includes(university.short) ? <Check size={16} /> : <Plus size={16} />}</button>)}</div>{cards.length ? <div className="university-compare-table"><div className="compare-labels"><span>Métrica</span><span>Oferta cargada</span><span>Nota mediana</span><span>Rendimiento</span><span>Abandono 1.º año</span><span>Graduación 4 años</span></div>{cards.map(card => <div className="university-compare-column" key={card.short}><b>{card.short}</b><h2>{card.name.replace('Universidad ', '')}</h2><strong>{card.count}</strong><span>{format(card.median)}</span><span>{format(card.performance)}</span><span>{format(card.dropout)}</span><span>{format(card.graduation)}</span></div>)}</div> : <div className="route-empty"><strong>Elige al menos una universidad.</strong><p>Las métricas mantienen su curso y cobertura para que la comparación sea interpretable.</p></div>}<div className="method-note"><X size={15} /> Rendimiento, abandono y graduación son agregados de universidad publicados por SIIU; no predicen el resultado de una titulación individual.</div></main></div>;
}
